PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS sources(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,url TEXT NOT NULL,license TEXT,retrieved_at TEXT);
CREATE TABLE IF NOT EXISTS vocabulary(id INTEGER PRIMARY KEY,jmdict_entry_id INTEGER,word TEXT NOT NULL,reading TEXT NOT NULL DEFAULT '',jlpt_level INTEGER NOT NULL CHECK(jlpt_level BETWEEN 1 AND 5),primary_pos TEXT,pos_group TEXT,verb_class TEXT,transitivity TEXT,adjective_class TEXT,is_common INTEGER NOT NULL DEFAULT 0 CHECK(is_common IN(0,1)),match_method TEXT,match_score REAL,source_id INTEGER REFERENCES sources(id));
CREATE UNIQUE INDEX IF NOT EXISTS idx_vocab_word_reading_level ON vocabulary(word,reading,jlpt_level);
CREATE INDEX IF NOT EXISTS idx_vocab_level ON vocabulary(jlpt_level);
CREATE INDEX IF NOT EXISTS idx_vocab_word ON vocabulary(word);
CREATE INDEX IF NOT EXISTS idx_vocab_reading ON vocabulary(reading);
CREATE INDEX IF NOT EXISTS idx_vocab_jmdict ON vocabulary(jmdict_entry_id);
CREATE INDEX IF NOT EXISTS idx_vocab_pos_group ON vocabulary(pos_group);
CREATE INDEX IF NOT EXISTS idx_vocab_verb_class ON vocabulary(verb_class);
CREATE TABLE IF NOT EXISTS senses(id INTEGER PRIMARY KEY,vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,jmdict_sense_index INTEGER NOT NULL,meaning_en TEXT,meaning_zh TEXT,pos_text TEXT,pos_group TEXT,is_primary INTEGER NOT NULL DEFAULT 0 CHECK(is_primary IN(0,1)),review_status TEXT NOT NULL DEFAULT 'pending',translation_source TEXT,translation_note TEXT,UNIQUE(vocabulary_id,jmdict_sense_index));
CREATE INDEX IF NOT EXISTS idx_senses_vocab ON senses(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_senses_review ON senses(review_status);
CREATE TABLE IF NOT EXISTS meanings(id INTEGER PRIMARY KEY,vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,language TEXT NOT NULL,meaning TEXT NOT NULL,sense_index INTEGER NOT NULL DEFAULT 0,is_primary INTEGER NOT NULL DEFAULT 0 CHECK(is_primary IN(0,1)));
CREATE INDEX IF NOT EXISTS idx_meanings_vocab_lang ON meanings(vocabulary_id,language);
CREATE TABLE IF NOT EXISTS examples(id INTEGER PRIMARY KEY,vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,sense_id INTEGER REFERENCES senses(id) ON DELETE SET NULL,sentence_ja TEXT NOT NULL,sentence_zh TEXT,sentence_en TEXT,source TEXT,source_external_id TEXT,difficulty INTEGER);
CREATE INDEX IF NOT EXISTS idx_examples_vocab ON examples(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_examples_sense ON examples(sense_id);
CREATE TABLE IF NOT EXISTS tags(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS vocabulary_tags(vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,PRIMARY KEY(vocabulary_id,tag_id));
CREATE TABLE IF NOT EXISTS word_lists(id INTEGER PRIMARY KEY,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,source TEXT);
CREATE TABLE IF NOT EXISTS word_list_items(word_list_id INTEGER NOT NULL REFERENCES word_lists(id) ON DELETE CASCADE,vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,sort_order INTEGER,PRIMARY KEY(word_list_id,vocabulary_id));
CREATE TABLE IF NOT EXISTS metadata(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE VIRTUAL TABLE IF NOT EXISTS vocabulary_fts USING fts5(vocabulary_id UNINDEXED,word,reading,meaning_zh,meaning_en,tokenize='unicode61');
